string testData1 =
@"...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....";

string testData2 =
@"....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......";

var solutions = new AdventSolutions();
var today = solutions.GetDay(2023, 11);

await today.DownloadInputAsync();

// today.SetTestInput(testData1);
// today.Part1();
// today.Part2();

await today.CheckPart1Async();
await today.CheckPart2Async();

// await Task.WhenAll(solutions.Select(async day => { await day.CheckPart1Async(); await day.CheckPart2Async(); }));

// today.Benchmark();
